# Assignment 1 

## Prepared by Daniil Ruzhinskii
## Python Programming for Business Intelligence

In [159]:
import pandas as pd
import numpy as np

## Task 1 - list of dictionaries

In [160]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

### a) Filtering invalid transactions

In [161]:
#simple filter to remove transactions with negative price or quantity
#pointer to the another list object in memory, so it does not modify the original list of transactions
filtered_transactions = [t for t in transactions if t["price"]>0 and t["quantity"]>=0]

print(f"There are {len(filtered_transactions)} valid transactions and the breakdown is below:")
for transaction in filtered_transactions:
    print(f"Transaction ID {transaction['id']}: Price = {transaction['price']}, Quantity = {transaction['quantity']}")

There are 4 valid transactions and the breakdown is below:
Transaction ID 1: Price = 1200, Quantity = 2
Transaction ID 4: Price = 350, Quantity = 3
Transaction ID 5: Price = 1200, Quantity = 1
Transaction ID 6: Price = 75, Quantity = 10

### b) Filtering invalid transactions

In [162]:
#Calculating the total and adding it as a new key-value pair in the transaction dictionary
for transaction in filtered_transactions:
    transaction["total"] = transaction["price"] * transaction["quantity"]

#Print nice and tidy 
for transaction in filtered_transactions:
    print(f"Transaction ID {transaction['id']}: Total = {transaction['total']}")

Transaction ID 1: Total = 2400
Transaction ID 4: Total = 1050
Transaction ID 5: Total = 1200
Transaction ID 6: Total = 750

### c) Grouping by region

In [163]:
#initializing an empty dictionary to store the grouped regions
grouped_regions = {}

#grouping the transactions by region
for transaction in filtered_transactions:

    #placeholder to store the region of the current transaction
    region = transaction["region"]

    #if region was not appended earlier, create a new entry with current trasaction
    if region not in grouped_regions:
        grouped_regions[region] = [transaction]
    
    #otherwise, just append the transaction to the exisiting key in the dictionary
    else:
        grouped_regions[region].append(transaction)

#quick sanity check
print(grouped_regions)


#create a new dictionary to store the total revenue for each region
#later i will utilize grouped_regions so dont want to modify it 

total_revenue_regions= {}
#calculating the total revenue for each region and updating the dictionary 
# with the total revenue instead of the list of transactions
for region, transactions in grouped_regions.items():
    total_revenue = sum(t["total"] for t in transactions)
    total_revenue_regions[region] = total_revenue

#final
print(total_revenue_regions)

{'EU': [{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}], 'US': [{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}], 'APAC': [{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]}
{'EU': 3600, 'US': 1050, 'APAC': 750}

### d) Region with highest total revenue

In [164]:
#Initialize container for the maximum total of the region
region_max=0

#going though all transactions grouped by region
for region in grouped_regions:

    #summing over all transactions in the region
    region_total = sum(t["total"] for t in grouped_regions[region])

    #conditional statmeent if the total of the current region is higher
    #than previously set maximum
    if region_total>region_max:
        region_max = region_total
        max_region = region

print(f"The region with the highest total sales is {max_region} with a total of {region_max}.")

The region with the highest total sales is EU with a total of 3600.

## Task 2 - creating a function

In [165]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

In [166]:
def summarize_sales(sales):

    output_dict = {}

    quantity = len(sales)
    total = sum(sales)

    output_dict["total"] = total

    #well, we cannot calculate the average if either nominator or denominator is zero
    if quantity != 0 and total != 0:
        average = total / quantity
    else:
        raise ValueError("Quantity and total must be non-zero to calculate average.")
    
    output_dict["average"] = average

    #iterating through the sales to find the best day
    best_sale=max(sales)
    best_day=sales.index(best_sale) # we find the index of the best sale, which corresponds to the day 
    #number (starting from 0)
    

    # we add 1 to the index becuase otherwise the day number would start from 0
    #it is more intiutive to say that the best day is e.g. day 1, not day 0
    best_day += 1 


    output_dict["best_day"] = best_day

    #same as best day, but for the worst day
    worst_sale=min(sales)
    worst_day=sales.index(worst_sale)
    worst_day += 1
    output_dict["worst_day"] = worst_day

    above_average_count = [i for i, sale in enumerate(sales) if sale > average]

    output_dict["above_average_count"] = len(above_average_count)

    return output_dict

summarize_sales(sales)

{'total': 20510,
 'average': 1465.0,
 'best_day': 11,
 'worst_day': 4,
 'above_average_count': 7}

## Task 3 - Loops

In [167]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

### a) Passing

In [168]:
#just simple filter to get the students who passed the course
passing = [s for s in students if s["grade"] >= 50]

passing_names = [s["name"] for s in passing]
passing_names

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']

### b) Evaluation

In [169]:
#bind the thresholds for the grades to variables which can be later changed
excellent_grade = 80
pass_grade = 50 

#Waterfall statement to print the grade category for each student
for student in students:
    if student["grade"] >= excellent_grade:
        print(f"{student['name']}: Excellent")
    elif student["grade"] >= pass_grade:
        print(f"{student['name']}: Pass")
    else:
        print(f"{student['name']}: Fail")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass

### c)  Attendance count

In [170]:
#initialize attendnace count and minimum attendance threshold
attendance_count=0
attendance_min = 0.80

#add to the count if the student is below threshold
for student in students:
    if student["attendance"] < attendance_min:
        attendance_count += 1

print(f"There are {attendance_count} students with attendance rate below set minimum")

There are 4 students with attendance rate below set minimum

### d) Top student with a loop

In [171]:
hihgest_grade=0

#one could actually just record the top performing grade and then reference the student with that grade
for student in students:
    if student["grade"] > hihgest_grade:
        hihgest_grade = student["grade"]
        top_student = student
    else:
        continue 

print(f"The top student is {top_student['name']} with the grade {hihgest_grade}.")

The top student is Nina with the grade 95.

#### e) Top student with max() method 

If wee are due-diligent, we **actually find out that max function has arguments to play with** 
Here the argument of interest is **key**, which allows us to specify function how to evaluate each element before actually comparing them

In [172]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

In the function for **key** we specify to return the grade of the student, so that max function can compare the grades among all students and return the student with the highest grade

For the functionality to return a grade of the student **lambda** is efficient and simple

So essentially we are telling the max function to go through all students, evaluate them by their grade and return the student with the max grade.

**Essentially, the output is dictionary**

In [173]:

top_student=max(students, key=lambda s: s["grade"])
print(type(top_student))
print(f"The top student is {top_student['name']} with the grade {top_student['grade']}.")

<class 'dict'>
The top student is Nina with the grade 95.

## Task 4 - Class and methods

To complete this task I will be writing the code incrementally so that the progress is visible.

At the end of each sub-part I test out the functionality of the methods using the printouts

I decided to avoid the long function to keep the code readable and distinguishable

In [174]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

### a) Add asset

In [175]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
           self.holdings[ticker]["shares"] += shares #addon the passed number of shares if the ticker already exists
           self.holdings[ticker]["price_per_share"] = price_per_share  #Update to latest price
        else: 
           self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share} 
           #otherwise, create a new entry in the holdings dictionary
    
    #just for the testing purposes
    def display_holdings(self):
        print(f"Portfolio of {self.owner}:")
        for ticker, info in self.holdings.items():
            print(f"{ticker}: {info['shares']} shares at {info['price_per_share']} units of currencyper share")


american_portfolio = Portfolio("Daniil")
american_portfolio.add_asset("AAPL", 10, 150)

american_portfolio.add_asset("GOOGL", 5, 2800)
american_portfolio.add_asset("AAPL", 5, 155)

american_portfolio.display_holdings()

Portfolio of Daniil:
AAPL: 15 shares at 155 units of currencyper share
GOOGL: 5 shares at 2800 units of currencyper share

### b) Total value

As the price of the asset is allowed to be updated, the method total_values uses the latest recorded price entry.
Which is logical, because the market value of the holdings is not static - but marked to market

In [176]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
           self.holdings[ticker]["shares"] += shares #addon the passed number of shares if the ticker already exists
           self.holdings[ticker]["price_per_share"] = price_per_share  #Update to latest price
        else: 
           self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share} 
           #otherwise, create a new entry in the holdings dictionary

    #the desired total values, just iterating through the holdings and summing over the value of each asset
    #uses the latest recorded price of the asset 
    def total_value(self):
        total = 0
        for info in self.holdings.values():
            total += info["shares"] * info["price_per_share"]
        return (f"The total value of the portfolio is: {total} units of currency")

american_portfolio = Portfolio("Daniil")
american_portfolio.add_asset("AAPL", 10, 150)
american_portfolio.add_asset("GOOGL", 5, 2800)
american_portfolio.add_asset("AAPL", 5, 155)
print(american_portfolio.total_value())

The total value of the portfolio is: 16325 units of currency

### c) Most valuable

In [177]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
           self.holdings[ticker]["shares"] += shares #addon the passed number of shares if the ticker already exists
           self.holdings[ticker]["price_per_share"] = price_per_share  #Update to latest price
        else: 
           self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share} 
           #otherwise, create a new entry in the holdings dictionary
           
    def most_valuable(self):
        #initial placeholders to store the most valuable asset and its value
        most_valuable=None
        highest_value=0

        #iterating through the holdings to find the most valuable asset
        for ticker, info in self.holdings.items():
            #lookup current asset value 
            asset_value = info["shares"] * info["price_per_share"]

            if asset_value > highest_value:
                highest_value = asset_value
                most_valuable = ticker
        return (f"The most valuable asset in the portfolio is {most_valuable} with a total value of {highest_value} units of currency")


american_portfolio = Portfolio("Daniil")
american_portfolio.add_asset("AAPL", 10, 150)
american_portfolio.add_asset("GOOGL", 5, 2800)
american_portfolio.add_asset("AAPL", 5, 155)

american_portfolio.most_valuable()

'The most valuable asset in the portfolio is GOOGL with a total value of 14000 units of currency'

### d) Summary

In [178]:
from email.mime import message


class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
           self.holdings[ticker]["shares"] += shares #addon the passed number of shares if the ticker already exists
           self.holdings[ticker]["price_per_share"] = price_per_share  #Update to latest price
        else: 
           self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share} 
           #otherwise, create a new entry in the holdings dictionary
    def total_value(self):
        total = 0
        for info in self.holdings.values():
            total += info["shares"] * info["price_per_share"]
        return (f"The total value of the portfolio is: {total} units of currency")
    
    def __str__(self):
        total_assets = sum(info["shares"] for info in self.holdings.values())
        message = [f"Summary of the portfolio owned by {self.owner}:"]

        message.append(f"Total Number of Assets: {total_assets}")
        for ticker, info in self.holdings.items():
            message.append(f"Asset {ticker}: {info['shares']} shares at latest recorded price of "
                           f"{info['price_per_share']} units of currency per share")
        
        message.append(f"{self.total_value()}")

        return "\n".join(message)
    
    
american_portfolio = Portfolio("Daniil")
american_portfolio.add_asset("AAPL", 10, 150)
american_portfolio.add_asset("GOOGL", 5, 2800)
american_portfolio.add_asset("AAPL", 5, 155)


print(american_portfolio)

Summary of the portfolio owned by Daniil:
Total Number of Assets: 20
Asset AAPL: 15 shares at latest recorded price of 155 units of currency per share
Asset GOOGL: 5 shares at latest recorded price of 2800 units of currency per share
The total value of the portfolio is: 16325 units of currency

## Task 5 - Importing a module

In [179]:
import datetime
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

help(datetime.date)

Help on class date in module datetime:

class date(builtins.object)
 |  date(year, month, day) --> date object
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(...)
 |      Formats self with strftime.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __reduce__(...)
 |      __reduce__() -> (cls, state)
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  ctime(...)
 |      Return ctime() style string.
 |
 |  isocalendar(...)
 |      Return a named tuple containing ISO year, week number, and weekday.
 |
 |  isoformat(...)
 |      Return string in ISO 8601 format, YYYY-MM-DD.
 |
 |  isoweekday(...)
 |      Return the day of the week represented by the date.
 |      Monday == 1 ... Sunday == 7
 |
 |  replace(...)
 |      Return date with new specified fields.
 |
 |  strftime(...)
 |      format -> strftime() style string.
 |
 |  timetuple(...)
 |      Return time tuple, compatible with time.localtime().
 |
 |  toordinal(...)
 |      Return proleptic Gregorian ordinal.  January 1 of year 1 is day 1.
 |
 |  weekday(...)
 |      Return the day of the week represented by the date.
 |      Monday == 0 ... Sunday == 6
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  fromisocalendar(...) from builtins.type
 |      int, int, int -> Construct a date from the ISO year, week number and weekday.
 |
 |      This is the inverse of the date.isocalendar() function
 |
 |  fromisoformat(...) from builtins.type
 |      str -> Construct a date from a string in ISO 8601 format.
 |
 |  fromordinal(...) from builtins.type
 |      int -> date corresponding to a proleptic Gregorian ordinal.
 |
 |  fromtimestamp(timestamp, /) from builtins.type
 |      Create a date from a POSIX timestamp.
 |
 |      The timestamp is a number, e.g. created via time.time(), that is interpreted
 |      as local time.
 |
 |  today(...) from builtins.type
 |      Current date or datetime:  same as self.__class__.fromtimestamp(time.time()).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  day
 |
 |  month
 |
 |  year
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  max = datetime.date(9999, 12, 31)
 |
 |  min = datetime.date(1, 1, 1)
 |
 |  resolution = datetime.timedelta(days=1)

In [180]:
import datetime 

dated_orders = []

#function expects a special postional argument in the format of "YYYY-MM-DD" and returns a date object
#this is the limitation of the function, that it only works for this specific format, but it is sufficient for our purposes
def parse_date(date_str):
    date_obj = year,month,day = date_str.split("-")
    date_obj=datetime.date(int(year), int(month), int(day))
    return date_obj #convert to string because otherwise the method
    #returns the date object, which is not very readable in the output

In [181]:
for order in orders:
    date_str, product = order
    date_obj = str(parse_date(date_str))
    dated_orders.append((date_obj, product))
    
print(dated_orders)

[('2025-01-15', 'Laptop'), ('2025-01-22', 'Phone'), ('2025-02-03', 'Laptop'), ('2025-02-14', 'Tablet'), ('2025-03-01', 'Phone'), ('2025-03-10', 'Phone'), ('2025-03-22', 'Laptop'), ('2025-04-05', 'Monitor')]

In [182]:
#using same logic as in exercise 3e 
min_date=min(dated_orders, key=lambda order: order[0])[0]
max_date=max(dated_orders, key=lambda order: order[0])[0]

#so the function min and max actually return the date in the string format, which is not very intuitive
# so we need to convert it to the date object again, good that i created a function for that
print(min_date, type(min_date))
print(max_date, type(max_date))

min_date = parse_date(min_date)
max_date = parse_date(max_date)

#now the dates are actually in date format 

print(min_date, type(min_date))
print(max_date, type(max_date))

days = (max_date - min_date).days

print(f"The time span between the earliest and latest order is {days} days.")

2025-01-15 <class 'str'>
2025-04-05 <class 'str'>
2025-01-15 <class 'datetime.date'>
2025-04-05 <class 'datetime.date'>
The time span between the earliest and latest order is 80 days.

## Task 6 - Array operations and broadcasting

Rows - years
Columns - quarters

In [183]:
import numpy as np

revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

### a) Total annual revenue

We use axis=1 to aggregate over the columns, which correspond to the quarters so we get the total revenue for each year

The output shape is (3,) which is actually what we intended - we got 3 years originally

In [184]:
#
total_yearly_revenue = np.sum(revenue, axis=1)

#the output is the vector of the total revnues for each year
total_yearly_revenue

array([ 880,  950, 1080])

### b) Mean quarterly revenue
So here we aggregate over rows in order to get the mean revenue for each quarter across the years

In comparison to previous one, the shape of the array is (4,) which corresponds to 4 entries ie quarters

In [185]:
#use axis=0
mean_quarterly_revenue = np.mean(revenue, axis=0)

mean_quarterly_revenue

array([226.66666667, 260.        , 206.66666667, 276.66666667])

### c) Growth adjustment

The logic is to first isolate the revenue of 2024 by taking the last row with index -1 and all the columns using : operator

We will get an error if we try to print the shape of growth_rate, because it is a list, not a numpy array, so it does not have the attribute shape

Once the shapes are compatible, we can apply simple multiplication

**The multiplication works well even without converting growth_rate to a NumPy array**, because NumPy supports element-wise operations with array-like objects such as Python lists, as long as their shapes are compatible. In this case, both have length 4, so the operation proceeds without broadcasting issues. 

Converting growth_rate to a NumPy array is not required here, but is safer, it allows access to NumPy methods and allows memory efficiency if computations are longer

In [186]:
growth_rate = [1.05, 1.03, 1.08, 1.02]

revenue_2024 = revenue[-1,:] 


print(f"Shape of revenue_2024: {revenue_2024.shape}")

#will result in error 
#print(f"Shape of growth_rate: {growth_rate.shape}") 

#we need to convert the growth_rate to a numpy array to be able to perform element-wise multiplication
growth_rate = np.array(growth_rate)
print(f"Shape of growth_rate: {growth_rate.shape}") 


revenue_2024= revenue_2024 * growth_rate
print(f"Adjusted revenue for 2024: {revenue_2024}")

Shape of revenue_2024: (4,)
Shape of growth_rate: (4,)
Adjusted revenue for 2024: [262.5 298.7 248.4 316.2]

### d) Good quarters

I apply the step by step code production for the given task. basically one could stop already at the first 
sub-point where we get the revenues above the threshold, but in my opinion it is not very descriptive.

For data analysis it is preferred to identify the numbers with the mapped time entries, i.e years and quarters

In [187]:
revenue_threshold = 250

#when we are asked to use the boolean indexing, lets first create a boolean array that indicates 
#which elements of the revenue array are above the threshold
boolean_mask = revenue > revenue_threshold
print(boolean_mask)

#we can then use this boolean mask to filter the 
#revenue array and get only the values that are above the threshold
above_threshold_revenue = revenue[boolean_mask]
print(above_threshold_revenue)

[[False False False False]
 [False  True False  True]
 [False  True False  True]]
[260 270 290 310]

In [188]:
#we can also identify the year and quarter for each of the above threshold revenues using the same boolean mask
above_threshold_years = np.where(boolean_mask)[0]  # get the row indices (years)
above_threshold_quarters = np.where(boolean_mask)[1]  # get the column indices
print(f"Years for above threshold revenue: {above_threshold_years}")
print(f"Quarters for above threshold revenue: {above_threshold_quarters}")

Years for above threshold revenue: [1 1 2 2]
Quarters for above threshold revenue: [1 3 1 3]

In [189]:
#we can represent teh combined info in format of dictionary, where the keys 
#are the above threshold revenues and the values are tuples of (year, quarter)
above_threshold_info = {}
for i in range(len(above_threshold_revenue)):
    revenue_value = above_threshold_revenue[i]
    year = above_threshold_years[i]
    quarter = above_threshold_quarters[i]
    above_threshold_info[revenue_value] = (year, quarter)
print(f"Above threshold revenue info: {above_threshold_info}")

Above threshold revenue info: {260: (1, 1), 270: (1, 3), 290: (2, 1), 310: (2, 3)}

In [190]:
#and if we go even further, then we can mark years, i.e. year 0=2022, year 1=2023, year 2=2024, 
#and quarters as well, i.e. quarter 0=Q1, quarter 1=Q2, quarter 2=Q3, quarter 3=Q4
above_threshold_info_detailed = {}
for i in range(len(above_threshold_revenue)):
    revenue_value = above_threshold_revenue[i]
    year = above_threshold_years[i]
    quarter = above_threshold_quarters[i]
    year_label = f"202{year+2}"  # since year 0 corresponds to 2022
    quarter_label = f"Q{quarter+1}"  # since quarter 0 corresponds to Q1
    above_threshold_info_detailed[revenue_value] = (year_label, quarter_label)

print(f"Above threshold revenue info pretty: {above_threshold_info_detailed}")

Above threshold revenue info pretty: {260: ('2023', 'Q2'), 270: ('2023', 'Q4'), 290: ('2024', 'Q2'), 310: ('2024', 'Q4')}

## Task 7 - Pandas

In [191]:
data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

### a) New column salary per year exp

In [192]:
import pandas as pd
data = pd.DataFrame(data, index=data['employee'])

#we can drop the employee column because it is now the index of the dataframe
data.drop(columns='employee', inplace=True) 
data

     department  salary  years_exp  performance_score
Anna    Finance    4500          5                4.2
Erik  Marketing    4000          3                3.8
Mia     Finance    4800          7                4.5
Leo          IT    5200         10                4.0
Sara  Marketing    3900          2                3.5
Tom          IT    5100          8                4.9

In [193]:
#we can use the dictionary inheretance to create a new key-item pair in the dataframe
data['salary_per_year_exp'] = round(data['salary'] / data['years_exp'],0)

data

     department  salary  years_exp  performance_score  salary_per_year_exp
Anna    Finance    4500          5                4.2                900.0
Erik  Marketing    4000          3                3.8               1333.0
Mia     Finance    4800          7                4.5                686.0
Leo          IT    5200         10                4.0                520.0
Sara  Marketing    3900          2                3.5               1950.0
Tom          IT    5100          8                4.9                638.0

### b) Sprting by performance

In [194]:
#as we can see below the standard python methods for sorting do not work for dataframes,
#but we can use the built-in method of the dataframe to sort it by a specific column
#uncomment to see the error

#sorted_data = data.sorted(data, key=lambda data: data['performance_score'], reverse=True)
#sorted_data

In [195]:
help(data.sort_values)
#this is actually more intuitive and descriptive 
sorted_data = data.sort_values(by='performance_score', ascending=False)

#selecting only top perfoming 
#the selection works as simple as that because we slicing works on dfs as well
sorted_data[ :3]

Help on method sort_values in module pandas.core.frame:

sort_values(by: 'IndexLabel', *, axis: 'Axis' = 0, ascending: 'bool | list[bool] | tuple[bool, ...]' = True, inplace: 'bool' = False, kind: 'SortKind' = 'quicksort', na_position: 'str' = 'last', ignore_index: 'bool' = False, key: 'ValueKeyFunc | None' = None) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame({
    ...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    ...     'col2': [2, 1, 9, 8, 7, 4],
    ...     'col3': [0, 1, 9, 4, 2, 3],
    ...     'col4': ['a', 'B', 'c', 'D', 'e', 'F']
    ... })
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Sort by col1

    >>> df.sort_values(by=['col1'])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort by multiple columns

    >>> df.sort_values(by=['col1', 'col2'])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort Descending

    >>> df.sort_values(by='col1', ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    Putting NAs first

    >>> df.sort_values(by='col1', ascending=False, na_position='first')
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    Sorting with a key function

    >>> df.sort_values(by='col4', key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Natural sort with the key argument,
    using the `natsort <https://github.com/SethMMorton/natsort>` package.

    >>> df = pd.DataFrame({
    ...    "time": ['0hr', '128hr', '72hr', '48hr', '96hr'],
    ...    "value": [10, 20, 30, 40, 50]
    ... })
    >>> df
        time  value
    0    0hr     10
    1  128hr     20
    2   72hr     30
    3   48hr     40
    4   96hr     50
    >>> from natsort import index_natsorted
    >>> df.sort_values(
    ...     by="time",
    ...     key=lambda x: np.argsort(index_natsorted(df["time"]))
    ... )
        time  value
    0    0hr     10
    3   48hr     40
    2   72hr     30
    4   96hr     50
    1  128hr     20

     department  salary  years_exp  performance_score  salary_per_year_exp
Tom          IT    5100          8                4.9                638.0
Mia     Finance    4800          7                4.5                686.0
Anna    Finance    4500          5                4.2                900.0

### c) Loc selection

In [196]:
#we apply specific doublefiltering on the rows, and then select all the columns
finance_department = data.loc[(data['department'] == 'Finance') & (data['performance_score'] > 4.0), :]
finance_department

     department  salary  years_exp  performance_score  salary_per_year_exp
Anna    Finance    4500          5                4.2                900.0
Mia     Finance    4800          7                4.5                686.0

### d) Renaming column

In [197]:
help(data.rename)
sorted_data.rename(columns={'years_exp': 'experience_years'}, inplace=True)
sorted_data

Help on method rename in module pandas.core.frame:

rename(mapper: 'Renamer | None' = None, *, index: 'Renamer | None' = None, columns: 'Renamer | None' = None, axis: 'Axis | None' = None, copy: 'bool | None' = None, inplace: 'bool' = False, level: 'Level | None' = None, errors: 'IgnoreRaise' = 'ignore') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Rename columns or index labels.

    Function / dict values must be unique (1-to-1). Labels not contained in
    a dict / Series will be left as-is. Extra labels listed don't throw an
    error.

    See the :ref:`user guide <basics.rename>` for more.

    Parameters
    ----------
    mapper : dict-like or function
        Dict-like or function transformations to apply to
        that axis' values. Use either ``mapper`` and ``axis`` to
        specify the axis to target with ``mapper``, or ``index`` and
        ``columns``.
    index : dict-like or function
        Alternative to specifying axis (``mapper, axis=0``
        is equivalent to ``index=mapper``).
    columns : dict-like or function
        Alternative to specifying axis (``mapper, axis=1``
        is equivalent to ``columns=mapper``).
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis to target with ``mapper``. Can be either the axis name
        ('index', 'columns') or number (0, 1). The default is 'index'.
    copy : bool, default True
        Also copy underlying data.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
        If True then value of copy is ignored.
    level : int or level name, default None
        In case of a MultiIndex, only rename labels in the specified
        level.
    errors : {'ignore', 'raise'}, default 'ignore'
        If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
        or `columns` contains labels that are not present in the Index
        being transformed.
        If 'ignore', existing keys will be renamed and extra keys will be
        ignored.

    Returns
    -------
    DataFrame or None
        DataFrame with the renamed axis labels or None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis and
        "errors='raise'".

    See Also
    --------
    DataFrame.rename_axis : Set the name of the axis.

    Examples
    --------
    ``DataFrame.rename`` supports two calling conventions

    * ``(index=index_mapper, columns=columns_mapper, ...)``
    * ``(mapper, axis={'index', 'columns'}, ...)``

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Rename columns using a mapping:

    >>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
    >>> df.rename(columns={"A": "a", "B": "c"})
       a  c
    0  1  4
    1  2  5
    2  3  6

    Rename index using a mapping:

    >>> df.rename(index={0: "x", 1: "y", 2: "z"})
       A  B
    x  1  4
    y  2  5
    z  3  6

    Cast index labels to a different type:

    >>> df.index
    RangeIndex(start=0, stop=3, step=1)
    >>> df.rename(index=str).index
    Index(['0', '1', '2'], dtype='object')

    >>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
    Traceback (most recent call last):
    KeyError: ['C'] not found in axis

    Using axis-style parameters:

    >>> df.rename(str.lower, axis='columns')
       a  b
    0  1  4
    1  2  5
    2  3  6

    >>> df.rename({1: 2, 2: 4}, axis='index')
       A  B
    0  1  4
    2  2  5
    4  3  6

,department,salary,experience_years,performance_score,salary_per_year_exp
Tom,IT,5100,8,4.9,638.0
Mia,Finance,4800,7,4.5,686.0
Anna,Finance,4500,5,4.2,900.0
Leo,IT,5200,10,4.0,520.0
Erik,Marketing,4000,3,3.8,1333.0
Sara,Marketing,3900,2,3.5,1950.0

### e) iloc application

In [198]:
#I assume we do not want to hardcode the column indices
#instead specifying the desired columns is more robust and flexible 
#it doesnt require the manual search
desired_columns = ['salary', 'performance_score']

#we use the built-in method of the dataframe to get the column indices for the desired columns
column_indices = [data.columns.get_loc(col) for col in desired_columns]

#voila
data.iloc[:4, column_indices]

      salary  performance_score
Anna    4500                4.2
Erik    4000                3.8
Mia     4800                4.5
Leo     5200                4.0

## Task 8 - More pandas

In [199]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

### a) Create a DF

In [200]:
#first got to inspect data types of all variables to make sure they are in the 
#expected format for the later calculations
print(f" Type for days: {type(days)}")
print(f" Type for visitors: {type(visitors)}")
print(f" Type for conversion_rate: {type(conversion_rate)}")
print(f" Type for avg_order_value: {type(avg_order_value)}")

 Type for days: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
 Type for visitors: <class 'numpy.ndarray'>
 Type for conversion_rate: <class 'numpy.ndarray'>
 Type for avg_order_value: <class 'numpy.ndarray'>

In [201]:
#still inspecting outputs
print(days)
print(visitors)
print(conversion_rate)
print(avg_order_value)

DatetimeIndex(['2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
               '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13',
               '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17',
               '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21',
               '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25',
               '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29',
               '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02'],
              dtype='datetime64[ns]', freq='D')
[206 472 437 221 563 288 302 273 333 270 339 524 380 569 379 310 515 527
 544 555 210 405 307 297 296 529 516 285]
[0.0645 0.0578 0.0756 0.0339 0.0679 0.0511 0.0339 0.03   0.0499 0.055
 0.0311 0.0209 0.0483 0.0637 0.0751 0.0575 0.075  0.0719 0.0331 0.072
 0.0638 0.0367 0.0678 0.0719 0.038  0.0516 0.0243 0.055 ]
[64.3  48.44 43.26 43.61 49.39 46.07 72.9  42.82 50.33 50.28 50.28 50.55
 45.18 44.17 41.38 35.12 52.16 59.84 44.57 44.41 46.84 45.39 35.64 63.65
 54.39 42.88 52.97 45.62]

In [202]:
#one could convert first to series all the variables and then to data frame which would be robust
#but not necessary here, so lets just create a data frame directly from the arrays
data = pd.DataFrame({
    'date':days,
    'visitors': visitors,
    'conversion_rate': conversion_rate,
    'avg_order_value': avg_order_value, 
}).set_index('date')

data

            visitors  conversion_rate  avg_order_value
date
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39
2025-01-11       288           0.0511            46.07
2025-01-12       302           0.0339            72.90
2025-01-13       273           0.0300            42.82
2025-01-14       333           0.0499            50.33
2025-01-15       270           0.0550            50.28
2025-01-16       339           0.0311            50.28
2025-01-17       524           0.0209            50.55
2025-01-18       380           0.0483            45.18
2025-01-19       569           0.0637            44.17
2025-01-20       379           0.0751            41.38
2025-01-21       310           0.0575            35.12
2025-01-22       515           0.0750            52.16
2025-01-23       527           0.0719            59.84
2025-01-24       544           0.0331            44.57
2025-01-25       555           0.0720            44.41
2025-01-26       210           0.0638            46.84
2025-01-27       405           0.0367            45.39
2025-01-28       307           0.0678            35.64
2025-01-29       297           0.0719            63.65
2025-01-30       296           0.0380            54.39
2025-01-31       529           0.0516            42.88
2025-02-01       516           0.0243            52.97
2025-02-02       285           0.0550            45.62

### b) Computing new columns

In [203]:
#To make sure calculation is robust, i will cast the expected datatypes for the columns in question

data['visitors']= data['visitors'].astype(int)
data['conversion_rate'] = data['conversion_rate'].astype(float)

#creating conversions
data['conversions'] = (data['visitors'] * data['conversion_rate']).round(0)

In [204]:
#creating daily revenue, not rounded because not asked
data['daily_revenue'] = (data['conversions'] * data['avg_order_value'])
data

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13.0,835.90
2025-01-07,472,0.0578,48.44,27.0,1307.88
2025-01-08,437,0.0756,43.26,33.0,1427.58
2025-01-09,221,0.0339,43.61,7.0,305.27
2025-01-10,563,0.0679,49.39,38.0,1876.82
2025-01-11,288,0.0511,46.07,15.0,691.05
2025-01-12,302,0.0339,72.90,10.0,729.00
2025-01-13,273,0.0300,42.82,8.0,342.56
2025-01-14,333,0.0499,50.33,17.0,855.61
2025-01-15,270,0.0550,50.28,15.0,754.20
2025-01-16,339,0.0311,50.28,11.0,553.08
2025-01-17,524,0.0209,50.55,11.0,556.05
2025-01-18,380,0.0483,45.18,18.0,813.24
2025-01-19,569,0.0637,44.17,36.0,1590.12
2025-01-20,379,0.0751,41.38,28.0,1158.64
2025-01-21,310,0.0575,35.12,18.0,632.16
2025-01-22,515,0.0750,52.16,39.0,2034.24
2025-01-23,527,0.0719,59.84,38.0,2273.92
2025-01-24,544,0.0331,44.57,18.0,802.26
2025-01-25,555,0.0720,44.41,40.0,1776.40
2025-01-26,210,0.0638,46.84,13.0,608.92
2025-01-27,405,0.0367,45.39,15.0,680.85
2025-01-28,307,0.0678,35.64,21.0,748.44
2025-01-29,297,0.0719,63.65,21.0,1336.65
2025-01-30,296,0.0380,54.39,11.0,598.29
2025-01-31,529,0.0516,42.88,27.0,1157.76
2025-02-01,516,0.0243,52.97,13.0,688.61
2025-02-02,285,0.0550,45.62,16.0,729.92